package com.mvc.beans;
// Generated 23 Sep, 2018 2:17:11 PM by Hibernate Tools 4.3.1



/**
 * Userlogin generated by hbm2java
 * @Author Amit Gunjal
 */
public class Userlogin  implements java.io.Serializable {

    private static final long serialVersionUID = 1L;

     private String id;
     private String username;
     private String password;

    public Userlogin() {
    }

    public Userlogin(String id, String username, String password) {
       this.id = id;
       this.username = username;
       this.password = password;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


